- targets:
    - "10.0.0.10:9100"
  labels:
    env: "si-principal"
    role: "dns"
    hostname: "dns-01"
    provisioned_by: "ansible"

- targets:
    - "10.0.0.11:9100"
  labels:
    env: "si-principal"
    role: "dhcp"
    hostname: "dhcp-01"
    provisioned_by: "ansible"

- targets:
    - "10.0.0.20:9100"
  labels:
    env: "si-principal"
    role: "web"
    hostname: "web-01"
    provisioned_by: "ansible"

- targets:
    - "10.0.0.21:9100"
  labels:
    env: "si-principal"
    role: "mail"
    hostname: "mail-01"
    provisioned_by: "ansible"
