global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "si-projet"
    env: "production"

rule_files:
  - "/etc/prometheus/rules/alerting.yml"
  - "/etc/prometheus/rules/recording.yml"

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/si.yml"
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.*"
        replacement: "$1"

  - job_name: "honeypot"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/honeypot.yml"
        refresh_interval: 15s
    scrape_interval: 5s

  - job_name: "dns"
    static_configs:
      - targets: ["dns01:9119"]
        labels:
          role: "dns"

  - job_name: "mail"
    static_configs:
      - targets: ["mail01:9154"]
        labels:
          role: "mail"
