{
 "title": "Dashboard - Loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fréquence attaques SSH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({job=\"syslog\"} |= \"Failed password\" [5m]))"
    }
   ]
  },
  {
   "title": "Activité honeypot",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"honeypot\"}"
    }
   ]
  },
  {
   "title": "Tentatives SSH — 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\"} |= \"Failed password\" [24h]))"
    }
   ]
  },
  {
   "title": "Tentatives SSH en temps réel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"syslog\"} |= \"Failed password\""
    }
   ]
  }
 ]
}