{
 "title": "Dashboard - Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Trafic réseau KB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[5m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel état machines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM disponible %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "instance:memory_available:ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU par machine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "instance:cpu_usage:rate5m", "legendFormat": "__auto" }
   ]
  }
 ]
}