module(load="imudp")
input(type="imudp" port="514")

template(name="RemoteHostFile" type="string"
  string="/var/log/syslog-remote/%HOSTNAME%/%PROGRAMNAME%.log")

if $hostname == 'pfSense.home.arpa' then {
    action(type="omfile" dynaFile="RemoteHostFile")
    stop
}

if $fromhost-ip != '127.0.0.1' then {
    action(type="omfile" dynaFile="RemoteHostFile")
    stop
}module(load="imudp")
input(type="imudp" port="514")

template(name="RemoteHostFile" type="string"
  string="/var/log/syslog-remote/%HOSTNAME%/%PROGRAMNAME%.log")

if $hostname == 'pfSense.home.arpa' then {
    action(type="omfile" dynaFile="RemoteHostFile")
    stop
}

if $fromhost-ip != '127.0.0.1' then {
    action(type="omfile" dynaFile="RemoteHostFile")
    stop
}ruleset(name="remote"){
  action(type="omfwd" Target="localhost" Port="1514" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")
}

# Utilise les modules imudp/imtcp déjà chargés par la config par défaut
# et les rattache au ruleset "remote"
$InputUDPServerBindRuleset remote
$UDPServerRun 514

$InputTCPServerBindRuleset remote
$InputTCPServerRun 514
