ruleset(name="remote"){
  action(type="omfwd" Target="localhost" Port="1514" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")
}

# Utilise les modules imudp/imtcp déjà chargés par la config par défaut
# et les rattache au ruleset "remote"
$InputUDPServerBindRuleset remote
$UDPServerRun 514

$InputTCPServerBindRuleset remote
$InputTCPServerRun 514
