server:
  http_listen_port: 9080
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

scrape_configs:

  # ── Journald (systemd) ─────────────────────────────────────
  - job_name: "journald"
    journal:
      max_age: 12h
      labels:
        job: "journald"
        host: "monitoring"
    pipeline_stages:
      - labels:
          host: __syslog_hostname__
          program: __syslog_appname__

  # ── Cowrie JSON ────────────────────────────────────────────
  - job_name: "honeypot-cowrie"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "honeypot"
          type: "cowrie"
          __path__: /var/log/cowrie/cowrie.json
    pipeline_stages:
      - json:
          expressions:
            eventid: eventid
            src_ip: src_ip
            username: username
            password: password
            protocol: protocol
      - labels:
          eventid:
          src_ip:
          protocol:
# -------------
  - job_name: "syslog"
    syslog:
      listen_address: "0.0.0.0:514"
      listen_protocol: udp
      idle_timeout: 60s
      use_rfc5424_message: false
      labels:
        job: "syslog"


